### ISSUE TITLE
Source code gave me a seizure

### ISSUE THREAD

**Issue by kenan238** [error4OA/iconifier#1]
do fix

**Comment by error4OA** [comment]
how can i fix it its the way it is

**Comment by kenan238** [comment]
make it not hoerible

**Comment by error4OA** [comment]
its the way it is, cant fix it

**Comment by kenan238** [comment]
refactor it

**Comment by error4OA** [comment]
im not gonna rewrite the entire thing bruh

**Comment by kenan238** [comment]
dont let the [Technical debt](https://en.wikipedia.org/wiki/Technical_debt) catch up
